### ISSUE TITLE
Could not initialize GL extensions

### ISSUE THREAD

**Issue by edwinyi** [YunzhuLi/PyFleX#1]
I follow the steps of "Compile PyFleX with CMake & Pybind11" to install pyflex. After the installation, i have problem to run the example "test_FluidFall.py". The message shows in the terminal is in the following.

Could not initialize GL extensions
Segmentation fault (core dumped)

Many thanks if anyone can help me solve the issue.

**Comment by YunzhuLi** [comment]
Can you let me know the version of Ubuntu, Nvidia driver, and CUDA you are using?
The repo is tested to work well on Ubuntu 16.04, Nvidia driver 390.87, and CUDA V9.1.85.

**Comment by edwinyi** [comment]
> Nvidia driver

Hi Yunzhu,
I worked on Ubuntu 16.04, Nvidia driver 390.77, and CUDA V9.0.176.
I also tried the steps of "Compile and play with the original demo provided by NVIDIA FleX" and I have the same error messages. 
Thanks!

**Comment by YunzhuLi** [comment]
Would you please install CUDA 9.1 and try again?

**Comment by YunzhuLi** [comment]
We have reproduced your error using CUDA 9.0. Please try CUDA 9.1 instead.

**Comment by edwinyi** [comment]
> We have reproduced your error using CUDA 9.0. Please try CUDA 9.1 instead.

Thanks, Yunzhu. I will give a try.

**Comment by edwinyi** [comment]
It works. Thanks Yunzhu!

**Comment by YunzhuLi** [comment]
We now support compiling PyFleX using docker, and using the functionalities outside docker. Following is a detailed instruction:
[https://github.com/YunzhuLi/PyFleX/blob/master/bindings/docs/docker.md](https://github.com/YunzhuLi/PyFleX/blob/master/bindings/docs/docker.md)

**Comment by sjtuchenye** [comment]
I am using Ubuntu16.04, nvidia-440 and cuda-9.1. But I also have such issue, could you please tell me how to solve?

**Comment by sjtuchenye** [comment]
> I am using Ubuntu16.04, nvidia-440 and cuda-9.1. But I also have such issue, could you please tell me how to solve?

Oh I have solved it. It is because I use sudo ./NVIDIA-Linux-440.run --no-opengl-files when install nvidia driver. It works by reinstalling the driver without the command '--no-opengl-files'.
