### ISSUE TITLE
compile the headless mode

### ISSUE THREAD

**Issue by Yusufma03** [YunzhuLi/PyFleX#2]
Hi Yunzhu,

I'm wondering if it is possible to disable the display and compile the NVidia Flex in a headless mode such that we could run the simulation faster without generating images. I really appreciate it if you could give me some suggestions on this. 

Thanks a lot

**Comment by YunzhuLi** [comment]
Hi Xiao, Xingyu from CMU has built on top of this repo and developed SoftGym, which provides several benchmarking environments and supports headless mode: [https://github.com/Xingyu-Lin/softgym](https://github.com/Xingyu-Lin/softgym). You may consider taking a look at their repo.

**Comment by Yusufma03** [comment]
Hi Yunzhu, thanks for the update. I'm using it now and it works like a charm.
