### ISSUE TITLE
could not run pyflex examples

### ISSUE THREAD

**Issue by blue-rabbitt** [YunzhuLi/PyFleX#4]
Hi, I've followed the new document (https://github.com/YunzhuLi/PyFleX/blob/master/bindings/docs/docker.md) and there seems to be no problem compiling PyFlex in the docker environment but I'm still getting the segmentation fault when running python test_FluidFall.py with the message 'Unable to initialize SDLCould not initialize GL extensions'.
My settings are Ubuntu 16.04, Python 3.7, Pytorch 1.4.0.
Thanks!

**Comment by YunzhuLi** [comment]
Hi, is your issue resolved? Please make sure you have CUDA support. Also, you will need to move outside the docker and respecify the environment variables after the compilation.

**Comment by blue-rabbitt** [comment]
Thank you, I just re-installed everything, including CUDA and it was ok.
