### ISSUE TITLE
How to control the view?

### ISSUE THREAD

**Issue by syguan96** [YunzhuLi/PyFleX#7]
Hi yunzhu @YunzhuLi, thanks for your contribution. I'm new to this tool. Could you tell me how to control the viewpoint?

**Comment by YunzhuLi** [comment]
The projection matrix and the view matrix control the viewpoint. You may consider changing them directly in the cpp file or add a binding to support adjustments on the python side, which I haven't included in the public version of this repo.[https://github.com/YunzhuLi/PyFleX/blob/1391799c77b0bd8f5ab5a2a01f1f2ee64fb5a929/bindings/pyflex.cpp#L1322](https://github.com/YunzhuLi/PyFleX/blob/1391799c77b0bd8f5ab5a2a01f1f2ee64fb5a929/bindings/pyflex.cpp#L1322)
